---
- name: Getting security groups per instance
  include_tasks: security-group-modify-include.yaml
  with_items: "{{ hostvars[inventory_hostname].ec2_security_group_names.split(',') }}"
  loop_control:
    loop_var: ec2_ins_secgr